version: '2'
networks:
  web:
  db:
volumes:
  mysql-data:
    driver: local
services:
  web:
    build: .
    container_name: web
    networks:
      - web
      - db
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.7.13
    container_name: db
    networks:
      - db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password