version: '2'
networks:
  web:
  db:
volumes:
  mysql-data:
    driver: local
services:
  web:
    build: .
    container_name: web
    networks:
      - web
      - db
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build: db
    container_name: db
    networks:
      - db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat
      MYSQL_USER: user
      MYSQL_PASSWORD: password