version: '2'
networks:
  go_web:
  db:

services:
  go_web:
    build: .
    container_name: go_web
    networks:
      - go_web
      - db
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.7.13
    container_name: db
    networks:
      - db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password